[project]
name = "t-rex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "numba>=0.61.2",
    "numpy>=2.2.6",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
    "pydantic>=2.11.7",
    "pytesseract>=0.3.13",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "regex>=2025.9.1",
    "requests>=2.32.5",
    "slowapi>=0.1.9",
    "starlette>=0.47.3",
    "uvicorn>=0.35.0",
]
